// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hero-variants/CenteredBold.tsx": () => import("../components/mockups/hero-variants/CenteredBold.tsx"),
  "./components/mockups/hero-variants/MeshGradient.tsx": () => import("../components/mockups/hero-variants/MeshGradient.tsx"),
  "./components/mockups/hero-variants/SplitLayout.tsx": () => import("../components/mockups/hero-variants/SplitLayout.tsx")
};
